name: mymensa
description: "Organiser for your caferteria and daily food plan."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.0.7
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0
  build_runner: ^2.4.7
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/4xtransparent/mymensa4@4x.png

